spring:
  application:
    name: risk-engine
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8889}

server:
  port: 6000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
