spring:
  datasource:
    url: jdbc:postgresql://backup-service-db:5432/backupdb
    username: postgres
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

backup:
  backup-directory: /app/backups
  retention-days: 30
