spring:
  application:
    name: reference-service
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8889}
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

